### ISSUE TITLE
uglify-js does not yet support ES6

### ISSUE THREAD

**Issue by pejalo** [denar90/brunch-with-marionettejs#27]
`brunch build --production` fails with a syntax error. Removing `uglify-js-brunch` fixes the issue.

Apparently this is the place to track ES6 support: https://github.com/mishoo/UglifyJS2/issues/448

**Comment by ghost** [comment]
https://www.npmjs.com/package/uglify-js-harmony

**Comment by denar90** [comment]
Thx guys 👍  I'll look at it asap :)

**Comment by denar90** [comment]
Just updated stuff. `brunch build --production` minifies js... 

@pejalo which node version do you use?

**Comment by pejalo** [comment]
Thanks @denar90 ! I'm on node 7.3.0

**Comment by denar90** [comment]
@pejalo, Is it working for you now?

**Comment by pejalo** [comment]
@denar90 Yep! Thank you!

**Comment by denar90** [comment]
👍
